### ISSUE TITLE
Align the arrows in the middle by default ?

### ISSUE THREAD

**Issue by drupol** [OrangeX4/typst-pinit#2]
Hello,

When using Pinit with a trivial example, as such:

```
$#pin(1)f#pin(2)\(#pin(3)x#pin(4)\) = #pin(5)x#pin(6)^2$
```

![image](https://github.com/OrangeX4/typst-pinit/assets/252042/fbc8c82a-4d89-4d02-b1e4-cc1158d6535d)

Do you think it would it be possible to align the arrows differently? I would like them to be in the middle of the pins instead of pointing to a specific `pin`...  and to make that behaviour the default.

Do you have a solution for that?

**Comment by OrangeX4** [comment]
I don't think there's an easy way to do it at the moment, some workarounds are

```typst
#import "@preview/pinit:0.1.4": *

$#pin(1)f#pin(2)\(#pin(3)x#pin(4)\) = #pin(5)x#pin(6)^2$

#pinit-highlight(1, 6)

#let mean(..args) = args.pos().sum() / args.pos().len()

#pinit((1, 6), locs => absolute-place([↑], dx: mean(..locs.map(loc => loc.x)), dy: mean(..locs.map(loc => loc.y))))
```

I'll consider adding built-in support in the future.

**Comment by drupol** [comment]
Hey thanks for this!

I tested the workaround but I couldn't get it working as I wanted. It's not a big deal anyway.

> I'll consider adding built-in support in the future.

That would definitely be great, I'm pretty sure this will help some other users too.

Thanks!

**Comment by OrangeX4** [comment]
done in 0.2.0

**Comment by drupol** [comment]
Thank you!
