### ISSUE TITLE
Adding two arrowheads to pinit-arrow

### ISSUE THREAD

**Issue by psads-git** [OrangeX4/typst-pinit#4]
Apparently, `pinit-arrow` only draws single-arrowhead arrows. In some contexts, a double-arrowhead arrow is needed, as is the case here:

[Connecting tables cells with arrows](https://github.com/typst/typst/discussions/4510#discussioncomment-9975035)

I have created `pinit-arrow2`, which does exactly that:

[`pinit-arrow2`](https://github.com/typst/typst/discussions/4510#discussioncomment-9978914)

If you find it useful, please feel free to add it to your package.

Have a nice day!

**Comment by OrangeX4** [comment]
Sorry for such a late reply. I think this code is good and I will add it in the next version, thanks!

**Comment by psads-git** [comment]
You are welcome, @OrangeX4!

**Comment by OrangeX4** [comment]
done in 0.2.0
